In [1]:
import tensorflow as tf
print("TensorFlow version: ", tf.__version__)

TensorFlow version:  2.3.1


In [2]:
# Cerate 2 constant tensors and performs the multiplication
node1 = tf.constant(3.0,tf.float32)
node2 = tf.constant(4,tf.float32)
print("---------Normal print command----------------------------")
print(node1,node2)
c = node1 * node2
print("---------tf.print to run graph---------------------------")
tf.print(node1)
tf.print(node2)
tf.print(c)

---------Normal print command----------------------------
tf.Tensor(3.0, shape=(), dtype=float32) tf.Tensor(4.0, shape=(), dtype=float32)
---------tf.print to run graph---------------------------
3
4
12


In [3]:
# Cerate the 3 constant node and perform mul operation on a,b , 2. Perform the add operation on b,c 3. Pefrom substraction of 2 and 3

a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(4)

d = tf.multiply(a,b)
tf.print(d)
e = tf.add(b,c)
tf.print(e)
final = tf.subtract(d,e)
tf.print(final)


6
7
-1


In [4]:
# using Placeholder variables

tf.version

<module 'tensorflow._api.v2.version' from 'C:\\Users\\91805\\Documents\\AnacondaSetup\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>

In [5]:
# Another Sample Example.

c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
d = tf.constant([[1.0, 1.0], [0.0, 1.0]])
e = tf.matmul(c, d)
print(e)
# Lets check the type for e

type(e)
print(e.shape)


tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)
(2, 2)


In [6]:
# PlaceHolders
# in below example we have given placeholder for 3*3 array
tf.compat.v1.disable_eager_execution()
a = tf.compat.v1.placeholder(tf.int32 , shape=(3,3))
b = tf.constant(3)

c = tf.multiply(b,a)

with tf.compat.v1.Session() as sess:
    print(sess.run(c,feed_dict={a:[[1,1,1],[2,2,2],[3,3,3]]}))


[[3 3 3]
 [6 6 6]
 [9 9 9]]


In [7]:
b

<tf.Tensor 'Const:0' shape=() dtype=int32>

In [8]:
# Linear regression Model with Optimization.
# We need y,x , W and b  
# The equation is y = Wx + b
# below step will just print the output of linear regression model.

x = tf.compat.v1.placeholder(tf.float32)
W = tf.Variable([0.3],tf.float32)
b = tf.Variable([-0.3],tf.float32)
y = tf.compat.v1.placeholder(tf.float32)
linear_model = W*x + b

init = tf.compat.v1.global_variables_initializer()

with tf.compat.v1.Session() as sess:
    sess.run(init)
    print(sess.run(linear_model,feed_dict={x:[1,2,3,4,5]}))


[0.         0.3        0.6        0.90000004 1.2       ]


In [9]:
# Compute the Loss 


squred_loss = tf.square(linear_model - y)
total_loss = tf.reduce_sum(squred_loss)

with tf.compat.v1.Session() as sess:
    sess.run(init)
    print(sess.run(total_loss,feed_dict={x:[1,2,3,4,5],y:[1,2,3,5,0]}))


27.9


In [10]:
# Optimization using Gradient Decend Optimizer

Optimizer1 = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=0.01)
train = Optimizer1.minimize(total_loss)

with tf.compat.v1.Session() as sess:
    sess.run(init)
    for i in range(100000):
        sess.run(train,feed_dict={x:[1,2,3,4,5],y:[1,2,3,5,0]})
    
    print(sess.run([W,b]))

[array([0.10000081], dtype=float32), array([1.899997], dtype=float32)]


In [11]:
W = 0.10000081
b = 1.899997
linear_model = W*x + b

squred_loss = tf.square(linear_model - y)
total_loss = tf.reduce_sum(squred_loss)

with tf.compat.v1.Session() as sess:
    print(sess.run(total_loss,feed_dict={x:[1,2,3,4,5],y:[1,2,3,5,0]}))

14.700001


In [12]:
a = tf.Variable(2.0,tf.float16)

In [13]:
a

<tf.Variable 'Variable_2:0' shape=() dtype=float32>

In [14]:
print(a)

<tf.Variable 'Variable_2:0' shape=() dtype=float32>


In [23]:
X = tf.Variable(tf.random.normal([3,3]),(3,3))
print(X)

<tf.Variable 'Variable_5:0' shape=(3, 3) dtype=float32>


In [25]:
?tf.random.normal

In [32]:
a = tf.random.normal(shape=(3,3))

In [37]:
b= tf.Variable(a)
print(b)

<tf.Variable 'Variable_8:0' shape=(3, 3) dtype=float32>


In [42]:
a = tf.random.uniform(shape=[2,2],dtype=tf.float32)
print(a)

Tensor("random_uniform_3/RandomUniform:0", shape=(2, 2), dtype=float32)
